# Generated by Django 5.1.6 on 2025-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('bussiness', models.CharField(max_length=30)),
                ('client_chat', models.BooleanField()),
                ('time_of_chat', models.DateTimeField()),
            ],
        ),
    ]
